name: flutter_live_data_example
version: 1.0.0
author: Tanapoj Chaivanichanan <tanapoj@centrilliontech.co.th>
homepage: https://github.com/tanapoj/flutter_live_data

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_live_data: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: