name: flutter_live_data_example
version: 0.0.1
author: Tanapoj Chaivanichanan <tanapoj@centrilliontech.co.th>
homepage: https://www.centrilliontech.co.th

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_live_data: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: