name: flutter_live_data
description: LiveData for Flutter
version: 2.1.1
homepage: https://github.com/tanapoj/flutter_live_data

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: